### ISSUE TITLE
Test fails on ppc64be

### ISSUE THREAD

**Issue by luigino** [Martchus/cpp-utilities#10]
(but not on ppc64le) on openSUSE Tumbleweed, version 4.16.0.

See [log](https://github.com/Martchus/cpp-utilities/files/2716746/c%2B%2Butilities_ppc64be.txt).

**Comment by Martchus** [comment]
I'll have a look at it. Even though ppc64be is likely almost dead this code should be platform independent. Thanks for reporting.

**Comment by Martchus** [comment]
Fixed: https://github.com/Martchus/cpp-utilities/commit/a0dff23c26a0e6f5187efbb4eba8b4f94882d64b

Apparently big endian needs *no* special handing which I have been wrongly applied. Tested under Tumbleweed ppc64.
