### ISSUE TITLE
This package keeps breaking syncthingtray on the AUR

### ISSUE THREAD

**Issue by adolfintel** [Martchus/cpp-utilities#30]
Every time the version of this package gets updated I am unable to update your syncthingtray and syncthingtray-git packages from the AUR for a few days, sometimes weeks.

Since you're the maintainer for all of them, you should keep them updated or at least don't make them depend on a very specific version of this project.

**Comment by Martchus** [comment]
Sorry, but you must be doing something wrong. The version of c++utilities as currently present in the AUR allows you to build all packages that depend directly or indirectly on it

I always update packages as necessary in a timely manner and generally together as I release them on GitHub.

**Comment by adolfintel** [comment]
Right now I have syncthingtray-git installed, which installs qtutilities-git and c++utilities-git. I have an update available for c++utilities-git, which are your commits from yesterday, but I can't install it because pamac says (even after refreshing the AUR database):
```
Warning: installing c++utilities-git (1166.8bffc93-1) breaks dependency 'libc++utilities-git.so=5-64' required by qtutilites-git.
Add qt-utilities-git to remove.

could not satisfy dependencies:
- removing qtutilities-git breaks dependency 'libqtutilities-git.so=6-64' required by syncthingtray-git
- installing c++utilities-git (1166.8bffc93-1) breaks dependency 'libc++utilities-git.so=5-64' required by syncthingtray-git
- if possible, remove syncthingtray-git and retry
```

As far as I can tell there's no reason for this conflict, all three packages build and install just fine from command line, none of my other installed AUR packages shows this problem, and it happens on both Arch and Manjaro every few weeks. What am I doing wrong?

**Comment by Martchus** [comment]
The package will provide the dependency this AUR helper claims it wouldn't. File an issue with your AUR helper which apparently lacks support for soname-based dependencies.
